version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.11.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/angularapp.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/angularapp.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=angularapp -t angularapp .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/angularapp.tar angularapp
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/angularapp.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker tag angularapp khajapm/fullstackdemo-docker:dev
            docker login --username=${USER_NAME} --password=${USER_PASS}
            docker push khajapm/fullstackdemo-docker
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      
